name: Auto Bump Version

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      line_pattern:
        required: false
        default: "__version__ = '{version}'"
        type: string
      version_pattern:
        required: false
        default: "(.*)"
        type: string
          

jobs:
  bump_version:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: dryrun_bump
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Update file
        id: update
        run: |
          file_path="${{ inputs.file_path }}"
          line_pattern="${{ inputs.line_pattern}}"
          version_pattern="${{ inputs.version_pattern}}"
          new_version="${{ steps.dryrun_bump.outputs.new_version }}"

          if [ -z ${new_version+x} ]; then 
            echo "new_version is unset. Skipping";
            exit 0 
          else 
            echo "new_version is set to '$new_version'"; 
          fi

          
          echo file_path=$file_path, line_pattern=$line_pattern, version_pattern=$version_pattern, new_version=$new_version

          search_pattern="${line_pattern//\{version\}/$version_pattern}"
          new_version_line="${line_pattern//\{version\}/$new_version}"

          if ! grep -q -E "$search_pattern" "$file_path"; then
            echo "$search_pattern" not found in "$file_path"
            exit 1
          fi

          # Replace the search pattern with the new version line in the file
          sed -i -E "s/$search_pattern/$new_version_line/" "$file_path"

          if ! grep -q -E "$new_version_line" "$file_path"; then
            echo "$new_version_line" not found in "$file_path"
            exit 1
          else
            echo "Success"
          fi
          
      - name: Git add
        run: |
          git add "${{ inputs.file_path }}"

      - name: Build code
        run: |
          echo build code command

      - name: Run tests
        run: |
          echo test command
        
      - name: Configure git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        
            
      - name: Commit and push changes
        id: commit
        run: |
          # save last commit SHA value before commiting
          commit_sha=$(git rev-parse HEAD)
          echo "commit_sha=$commit_sha" >> "$GITHUB_OUTPUT"

          git commit -m "${{ steps.dryrun_bump.outputs.new_version }}"
          git push origin

          
          
        

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ steps.commit.outputs.commit_sha }}
      
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
