name: Auto Bump Version

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      line_pattern:
        required: false
        default: "__version__ = '{version}'"
        type: string
      version_pattern:
        required: false
        default: "(.*)"
        type: string
          

jobs:
  bump_version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump tag dry run
        id: bump
        run: |
          echo bump tag dry run command
          # Store the new version in the `new_version` output
          # echo "::set-output name=new_version::1.2.3"
          echo "new_version=1.2.3" >> $GITHUB_OUTPUT

      - name: Update file
        id: update
        run: |
          file_path="${{ inputs.file_path }}"
          line_pattern="${{ inputs.line_pattern}}"
          version_pattern="${{ inputs.version_pattern}}"
          new_version="${{ steps.bump.outputs.new_version }}"
          
          echo file_path=$file_path, line_pattern=$line_pattern, version_pattern=$version_pattern, new_version=$new_version

          search_pattern="${line_pattern//\{version\}/$version_pattern}"
          new_version_line="${line_pattern//\{version\}/$new_version}"

          if ! grep -q -E "$search_pattern" "$file_path"; then
            echo "$search_pattern" not found in "$file_path"
            exit 1
          fi

          # Replace the search pattern with the new version line in the file
          sed -i -E "s/$search_pattern/$new_version_line/" "$file_path"

          if ! grep -q -E "$new_version_line" "$file_path"; then
            echo "$new_version_line" not found in "$file_path"
            exit 1
          else
            echo "Success"
          fi
          
      - name: Git add
        run: |
          git add "${{ inputs.file_path }}"

      - name: Build code
        run: |
          echo build code command

      - name: Run tests
        run: |
          echo test command
        
      - name: Configure git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        
            
      - name: Commit and push changes
        run: |
          git commit -m "${{ steps.bump.outputs.new_version }}"
          git push origin
        

      - name: Create tag and release
        run: |
          echo create tag and release command
