name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  auto_bump:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout
      
      - name: Call Auto Bump
        uses: ./.github/workflows/auto-bump-version.yaml
        with:
          file_path: "src/__init__.py"
          line_pattern: "__version__ = '{version}'"
          version_pattern: "(.*)"
