name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  auto_bump:
    uses: ./.github/workflows/auto-bump-version.yml
    with:
      file_path: "src/__init__.py"
      line_pattern: "__version__ = '{version}'"
      version_pattern: "(.*)"
    secrets: inherit
    permissions: 
      contents: write
